---
- hosts: all
  remote_user: root

  vars:
    ntp_enabled: true
    ntp_manage_config: true
    ntp_servers: 
     - 0.pool.ntp.org iburst
     - 1.pool.ntp.org iburst
     - 2.pool.ntp.org iburst
     - 3.pool.ntp.org iburst

  roles:
    - ansible-role-ntp
